import json
import mysql.connector

# Ton JSON d'entrée
data = [{"site_id":1,"states":"-Ecuador"},{"site_id":2,"states":"-Ecuador"},{"site_id":3,"states":"-Germany"},{"site_id":4,"states":"-Canada"},{"site_id":8,"states":"-Tunisia"},{"site_id":9,"states":"-Ethiopia"},{"site_id":10,"states":"-Ethiopia"},{"site_id":12,"states":"-Ethiopia"},{"site_id":15,"states":"-Ethiopia"},{"site_id":17,"states":"-Ethiopia"},{"site_id":18,"states":"-Ethiopia"},{"site_id":19,"states":"-Ethiopia"},{"site_id":20,"states":"-Syrian Arab Republic"},{"site_id":21,"states":"-Syrian Arab Republic"},{"site_id":22,"states":"-Syrian Arab Republic"},{"site_id":23,"states":"-Syrian Arab Republic"},{"site_id":24,"states":"-Canada"},{"site_id":25,"states":"-Senegal"},{"site_id":26,"states":"-Senegal"},{"site_id":27,"states":"-United States of America"},{"site_id":28,"states":"-United States of America"},{"site_id":29,"states":"-Poland"},{"site_id":30,"states":"-Poland"},{"site_id":31,"states":"-Poland"},{"site_id":32,"states":"-Poland"},{"site_id":33,"states":"-Belarus-Poland"},{"site_id":34,"states":"-Ghana"},{"site_id":35,"states":"-Ghana"},{"site_id":36,"states":"-Tunisia"},{"site_id":37,"states":"-Tunisia"},{"site_id":38,"states":"-Tunisia"},{"site_id":39,"states":"-United Republic of Tanzania"},{"site_id":42,"states":"-Bulgaria"},{"site_id":43,"states":"-Bulgaria"},{"site_id":44,"states":"-Bulgaria"},{"site_id":45,"states":"-Bulgaria"},{"site_id":55,"states":"-Norway"},{"site_id":58,"states":"-Norway"},{"site_id":59,"states":"-Norway"},{"site_id":63,"states":"-Democratic Republic of the Congo"},{"site_id":64,"states":"-Guatemala"},{"site_id":65,"states":"-Guatemala"},{"site_id":71,"states":"-Canada"},{"site_id":72,"states":"-Canada-United States of America"},{"site_id":75,"states":"-United States of America"},{"site_id":76,"states":"-United States of America"},{"site_id":78,"states":"-United States of America"},{"site_id":79,"states":"-Cyprus"},{"site_id":80,"states":"-France"},{"site_id":81,"states":"-France"},{"site_id":83,"states":"-France"},{"site_id":84,"states":"-France"},{"site_id":85,"states":"-France"},{"site_id":86,"states":"-Egypt"},{"site_id":87,"states":"-Egypt"},{"site_id":88,"states":"-Egypt"},{"site_id":89,"states":"-Egypt"},{"site_id":90,"states":"-Egypt"},{"site_id":91,"states":"-Holy See-Italy"},{"site_id":93,"states":"-Italy"},{"site_id":94,"states":"-Italy"},{"site_id":95,"states":"-Croatia"},{"site_id":96,"states":"-Serbia"},{"site_id":97,"states":"-Croatia"},{"site_id":98,"states":"-Croatia"},{"site_id":99,"states":"-Albania-North Macedonia"},{"site_id":100,"states":"-Montenegro"},{"site_id":102,"states":"-Algeria"},{"site_id":113,"states":"-Iran (Islamic Republic of)"},{"site_id":114,"states":"-Iran (Islamic Republic of)"},{"site_id":115,"states":"-Iran (Islamic Republic of)"},{"site_id":116,"states":"-Mali"},{"site_id":119,"states":"-Mali"},{"site_id":120,"states":"-Nepal"},{"site_id":121,"states":"-Nepal"},{"site_id":124,"states":"-Brazil"},{"site_id":125,"states":"-Montenegro"},{"site_id":129,"states":"-Honduras"},{"site_id":130,"states":"-Malta"},{"site_id":131,"states":"-Malta"},{"site_id":132,"states":"-Malta"},{"site_id":134,"states":"-United States of America"},{"site_id":135,"states":"-Panama"},{"site_id":136,"states":"-Democratic Republic of the Congo"},{"site_id":137,"states":"-Democratic Republic of the Congo"},{"site_id":138,"states":"-Pakistan"},{"site_id":139,"states":"-Pakistan"},{"site_id":140,"states":"-Pakistan"},{"site_id":143,"states":"-Pakistan"},{"site_id":144,"states":"-United Republic of Tanzania"},{"site_id":145,"states":"-Argentina"},{"site_id":147,"states":"-Australia"},{"site_id":148,"states":"-Jerusalem (Site proposed by Jordan)"},{"site_id":149,"states":"-Guatemala"},{"site_id":150,"states":"-United States of America"},{"site_id":151,"states":"-United States of America"},{"site_id":153,"states":"-Senegal"},{"site_id":154,"states":"-Australia"},{"site_id":155,"states":"-Côte d'Ivoire-Guinea"},{"site_id":156,"states":"-United Republic of Tanzania"},{"site_id":157,"states":"-Canada"},{"site_id":158,"states":"-Canada"},{"site_id":159,"states":"-Panama"},{"site_id":160,"states":"-France"},{"site_id":162,"states":"-France"},{"site_id":163,"states":"-France"},{"site_id":164,"states":"-France"},{"site_id":165,"states":"-France"},{"site_id":166,"states":"-Australia"},{"site_id":167,"states":"-Australia"},{"site_id":168,"states":"-Germany"},{"site_id":169,"states":"-Germany"},{"site_id":170,"states":"-Morocco"},{"site_id":171,"states":"-Pakistan"},{"site_id":173,"states":"-United Republic of Tanzania"},{"site_id":174,"states":"-Italy"},{"site_id":175,"states":"-Italy"},{"site_id":179,"states":"-Algeria"},{"site_id":180,"states":"-Haiti"},{"site_id":181,"states":"-Australia"},{"site_id":183,"states":"-Libya"},{"site_id":184,"states":"-Libya"},{"site_id":185,"states":"-Seychelles"},{"site_id":186,"states":"-Australia"},{"site_id":187,"states":"-Germany"},{"site_id":188,"states":"-Algeria"},{"site_id":189,"states":"-Brazil"},{"site_id":190,"states":"-Libya"},{"site_id":191,"states":"-Algeria"},{"site_id":192,"states":"-Yemen"},{"site_id":193,"states":"-Algeria"},{"site_id":194,"states":"-Algeria"},{"site_id":195,"states":"-Côte d'Ivoire"},{"site_id":196,"states":"-Honduras"},{"site_id":198,"states":"-United States of America"},{"site_id":199,"states":"-United Republic of Tanzania"},{"site_id":200,"states":"-Sri Lanka"},{"site_id":201,"states":"-Sri Lanka"},{"site_id":202,"states":"-Sri Lanka"},{"site_id":203,"states":"-France"},{"site_id":204,"states":"-Cuba"},{"site_id":205,"states":"-Costa Rica-Panama"},{"site_id":206,"states":"-Portugal"},{"site_id":208,"states":"-Afghanistan"},{"site_id":211,"states":"-Afghanistan"},{"site_id":216,"states":"-Bulgaria"},{"site_id":217,"states":"-Bulgaria"},{"site_id":219,"states":"-Bulgaria"},{"site_id":225,"states":"-Bulgaria"},{"site_id":227,"states":"-Côte d'Ivoire"},{"site_id":228,"states":"-France"},{"site_id":229,"states":"-France"},{"site_id":230,"states":"-France"},{"site_id":231,"states":"-India"},{"site_id":232,"states":"-India"},{"site_id":233,"states":"-India"},{"site_id":234,"states":"-India"},{"site_id":239,"states":"-India"},{"site_id":240,"states":"-India"},{"site_id":241,"states":"-India"},{"site_id":242,"states":"-India"},{"site_id":243,"states":"-India"},{"site_id":244,"states":"-India"},{"site_id":246,"states":"-India"},{"site_id":247,"states":"-India"},{"site_id":249,"states":"-India"},{"site_id":250,"states":"-India"},{"site_id":251,"states":"-India"},{"site_id":252,"states":"-India"},{"site_id":255,"states":"-India"},{"site_id":256,"states":"-Canada"},{"site_id":258,"states":"-France"},{"site_id":259,"states":"-United States of America"},{"site_id":260,"states":"-Ecuador"},{"site_id":261,"states":"-Seychelles"},{"site_id":262,"states":"-Sudan"},{"site_id":263,"states":"-Portugal"},{"site_id":264,"states":"-Portugal"},{"site_id":265,"states":"-Portugal"},{"site_id":266,"states":"-United States of America"},{"site_id":267,"states":"-Switzerland"},{"site_id":268,"states":"-Switzerland"},{"site_id":269,"states":"-Switzerland"},{"site_id":271,"states":"-Germany"},{"site_id":272,"states":"-Germany"},{"site_id":273,"states":"-Peru"},{"site_id":274,"states":"-Peru"},{"site_id":275,"states":"-Argentina-Brazil"},{"site_id":276,"states":"-Iraq"},{"site_id":277,"states":"-Iraq"},{"site_id":278,"states":"-Iraq"},{"site_id":280,"states":"-Democratic Republic of the Congo"},{"site_id":284,"states":"-Nepal"},{"site_id":285,"states":"-Colombia"},{"site_id":286,"states":"-Holy See"},{"site_id":287,"states":"-Libya"},{"site_id":288,"states":"-Germany"},{"site_id":289,"states":"-Malawi"},{"site_id":292,"states":"-Germany"},{"site_id":293,"states":"-Lebanon"},{"site_id":294,"states":"-Lebanon"},{"site_id":295,"states":"-Lebanon"},{"site_id":299,"states":"-Lebanon"},{"site_id":300,"states":"-Canada"},{"site_id":302,"states":"-Zimbabwe"},{"site_id":303,"states":"-Argentina"},{"site_id":304,"states":"-Canada"},{"site_id":306,"states":"-Zimbabwe"},{"site_id":307,"states":"-United States of America"},{"site_id":308,"states":"-United States of America"},{"site_id":309,"states":"-Brazil"},{"site_id":310,"states":"-Spain"},{"site_id":311,"states":"-Spain"},{"site_id":312,"states":"-Spain"},{"site_id":313,"states":"-Spain"},{"site_id":314,"states":"-Spain"},{"site_id":316,"states":"-Spain"},{"site_id":318,"states":"-Spain"},{"site_id":320,"states":"-Spain"},{"site_id":321,"states":"-Bangladesh"},{"site_id":322,"states":"-Bangladesh"},{"site_id":323,"states":"-Benin"},{"site_id":326,"states":"-Jordan"},{"site_id":327,"states":"-Jordan"},{"site_id":330,"states":"-Peru"},{"site_id":331,"states":"-Morocco"},{"site_id":332,"states":"-Tunisia"},{"site_id":333,"states":"-Peru"},{"site_id":334,"states":"-Brazil"},{"site_id":335,"states":"-India"},{"site_id":337,"states":"-India"},{"site_id":338,"states":"-India"},{"site_id":340,"states":"-India"},{"site_id":344,"states":"-France"},{"site_id":345,"states":"-France"},{"site_id":347,"states":"-Spain"},{"site_id":348,"states":"-Spain"},{"site_id":351,"states":"-Cyprus"},{"site_id":352,"states":"-Norway"},{"site_id":353,"states":"-United States of America"},{"site_id":354,"states":"-Canada-United States of America"},{"site_id":355,"states":"-Brazil"},{"site_id":356,"states":"-Turkey"},{"site_id":357,"states":"-Turkey"},{"site_id":358,"states":"-Turkey"},{"site_id":359,"states":"-Bulgaria"},{"site_id":361,"states":"-Portugal"},{"site_id":362,"states":"-Libya"},{"site_id":364,"states":"-Zimbabwe"},{"site_id":365,"states":"-Zimbabwe"},{"site_id":366,"states":"-Peru"},{"site_id":367,"states":"-Germany"},{"site_id":368,"states":"-Australia"},{"site_id":369,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":370,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":371,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":372,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":373,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":374,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":377,"states":"-Turkey"},{"site_id":378,"states":"-Spain"},{"site_id":379,"states":"-Spain"},{"site_id":380,"states":"-Spain"},{"site_id":381,"states":"-Spain"},{"site_id":383,"states":"-Spain"},{"site_id":384,"states":"-Spain"},{"site_id":385,"states":"-Yemen"},{"site_id":387,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":389,"states":"-Serbia"},{"site_id":390,"states":"-Slovenia"},{"site_id":392,"states":"-Greece"},{"site_id":393,"states":"-Greece"},{"site_id":394,"states":"-Italy"},{"site_id":395,"states":"-Italy"},{"site_id":398,"states":"-Italy"},{"site_id":400,"states":"-Hungary"},{"site_id":401,"states":"-Hungary"},{"site_id":402,"states":"-Peru"},{"site_id":403,"states":"-United Republic of Tanzania"},{"site_id":404,"states":"-Greece"},{"site_id":405,"states":"-Sri Lanka"},{"site_id":407,"states":"-Cameroon"},{"site_id":409,"states":"-United States of America"},{"site_id":410,"states":"-Mexico"},{"site_id":411,"states":"-Mexico"},{"site_id":412,"states":"-Mexico"},{"site_id":414,"states":"-Mexico"},{"site_id":415,"states":"-Mexico"},{"site_id":416,"states":"-Mexico"},{"site_id":417,"states":"-Spain"},{"site_id":419,"states":"-Canada"},{"site_id":420,"states":"-Bolivia (Plurinational State of)"},{"site_id":421,"states":"-New Zealand"},{"site_id":422,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":425,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":426,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":428,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":429,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":430,"states":"-Germany-United Kingdom of Great Britain and Northern Ireland"},{"site_id":433,"states":"-Oman"},{"site_id":434,"states":"-Oman"},{"site_id":437,"states":"-China"},{"site_id":438,"states":"-China"},{"site_id":439,"states":"-China"},{"site_id":440,"states":"-China"},{"site_id":441,"states":"-China"},{"site_id":442,"states":"-United States of America"},{"site_id":444,"states":"-Morocco"},{"site_id":445,"states":"-Brazil"},{"site_id":447,"states":"-Australia"},{"site_id":448,"states":"-Turkey"},{"site_id":449,"states":"-China"},{"site_id":450,"states":"-Sri Lanka"},{"site_id":451,"states":"-Sri Lanka"},{"site_id":452,"states":"-India"},{"site_id":454,"states":"-Greece"},{"site_id":455,"states":"-Greece"},{"site_id":456,"states":"-Greece"},{"site_id":460,"states":"-Cuba"},{"site_id":474,"states":"-Hungary"},{"site_id":475,"states":"-Central African Republic"},{"site_id":476,"states":"-Malawi"},{"site_id":479,"states":"-Lao People's Democratic Republic"},{"site_id":481,"states":"-Lao People's Democratic Republic"},{"site_id":482,"states":"-Mexico"},{"site_id":483,"states":"-Mexico"},{"site_id":484,"states":"-Turkey"},{"site_id":485,"states":"-Turkey"},{"site_id":486,"states":"-Australia"},{"site_id":487,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":488,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":491,"states":"-Greece"},{"site_id":492,"states":"-United States of America"},{"site_id":493,"states":"-Greece"},{"site_id":494,"states":"-Madagascar"},{"site_id":495,"states":"-France"},{"site_id":496,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":498,"states":"-Tunisia"},{"site_id":499,"states":"-Tunisia"},{"site_id":500,"states":"-Peru"},{"site_id":502,"states":"-Philippines"},{"site_id":505,"states":"-Portugal"},{"site_id":506,"states":"-Mauritania"},{"site_id":509,"states":"-Zambia-Zimbabwe"},{"site_id":511,"states":"-Greece"},{"site_id":514,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":515,"states":"-Germany"},{"site_id":516,"states":"-Mali"},{"site_id":517,"states":"-Greece"},{"site_id":518,"states":"-Spain"},{"site_id":522,"states":"-Spain"},{"site_id":524,"states":"-India"},{"site_id":526,"states":"-Dominican Republic"},{"site_id":527,"states":"-Ukraine"},{"site_id":529,"states":"-Bolivia (Plurinational State of)"},{"site_id":530,"states":"-Greece"},{"site_id":532,"states":"-Germany"},{"site_id":534,"states":"-Germany"},{"site_id":535,"states":"-Germany"},{"site_id":537,"states":"-Greece"},{"site_id":540,"states":"-Russian Federation"},{"site_id":541,"states":"-Lithuania"},{"site_id":543,"states":"-Uzbekistan"},{"site_id":544,"states":"-Russian Federation"},{"site_id":545,"states":"-Russian Federation"},{"site_id":546,"states":"-Germany"},{"site_id":547,"states":"-China"},{"site_id":548,"states":"-Peru"},{"site_id":549,"states":"-Italy"},{"site_id":550,"states":"-Italy"},{"site_id":551,"states":"-New Zealand"},{"site_id":554,"states":"-Mexico"},{"site_id":555,"states":"-Sweden"},{"site_id":556,"states":"-Sweden"},{"site_id":557,"states":"-Sweden"},{"site_id":558,"states":"-Sweden"},{"site_id":559,"states":"-Sweden"},{"site_id":560,"states":"-Mexico"},{"site_id":561,"states":"-Sri Lanka"},{"site_id":564,"states":"-Poland"},{"site_id":565,"states":"-Algeria"},{"site_id":566,"states":"-Bolivia (Plurinational State of)"},{"site_id":567,"states":"-Bolivia (Plurinational State of)"},{"site_id":569,"states":"-Albania"},{"site_id":570,"states":"-Albania"},{"site_id":573,"states":"-Niger"},{"site_id":574,"states":"-Thailand"},{"site_id":575,"states":"-Thailand"},{"site_id":576,"states":"-Thailand"},{"site_id":577,"states":"-Australia"},{"site_id":578,"states":"-Australia"},{"site_id":579,"states":"-Finland"},{"site_id":582,"states":"-Finland"},{"site_id":583,"states":"-Finland"},{"site_id":584,"states":"-Finland"},{"site_id":585,"states":"-Mexico"},{"site_id":586,"states":"-Pakistan"},{"site_id":588,"states":"-Romania"},{"site_id":590,"states":"-Thailand"},{"site_id":591,"states":"-Thailand"},{"site_id":592,"states":"-Indonesia"},{"site_id":593,"states":"-Indonesia"},{"site_id":595,"states":"-Greece"},{"site_id":596,"states":"-Romania"},{"site_id":597,"states":"-Romania"},{"site_id":598,"states":"-Romania"},{"site_id":599,"states":"-Mozambique"},{"site_id":600,"states":"-France"},{"site_id":601,"states":"-France"},{"site_id":602,"states":"-Uzbekistan"},{"site_id":603,"states":"-Uzbekistan"},{"site_id":604,"states":"-Russian Federation"},{"site_id":606,"states":"-Brazil"},{"site_id":608,"states":"-Indonesia"},{"site_id":609,"states":"-Indonesia"},{"site_id":611,"states":"-Yemen"},{"site_id":613,"states":"-Nicaragua"},{"site_id":614,"states":"-Turkey"},{"site_id":616,"states":"-Czechia"},{"site_id":617,"states":"-Czechia"},{"site_id":618,"states":"-Slovakia"},{"site_id":620,"states":"-Slovakia"},{"site_id":621,"states":"-Czechia"},{"site_id":622,"states":"-Slovakia"},{"site_id":623,"states":"-Germany"},{"site_id":624,"states":"-Germany"},{"site_id":625,"states":"-Belarus"},{"site_id":629,"states":"-Australia"},{"site_id":630,"states":"-Australia"},{"site_id":631,"states":"-Mexico"},{"site_id":632,"states":"-Russian Federation"},{"site_id":633,"states":"-Russian Federation"},{"site_id":634,"states":"-Russian Federation"},{"site_id":635,"states":"-France"},{"site_id":637,"states":"-China"},{"site_id":638,"states":"-China"},{"site_id":640,"states":"-China"},{"site_id":642,"states":"-Indonesia"},{"site_id":648,"states":"-Paraguay"},{"site_id":652,"states":"-Philippines"},{"site_id":653,"states":"-Philippines"},{"site_id":657,"states":"-Russian Federation"},{"site_id":658,"states":"-Venezuela (Bolivarian Republic of)"},{"site_id":659,"states":"-Ireland"},{"site_id":660,"states":"-Japan"},{"site_id":661,"states":"-Japan"},{"site_id":662,"states":"-Japan"},{"site_id":663,"states":"-Japan"},{"site_id":664,"states":"-Spain"},{"site_id":665,"states":"-Spain"},{"site_id":666,"states":"-Nepal"},{"site_id":668,"states":"-Cambodia"},{"site_id":669,"states":"-Spain"},{"site_id":670,"states":"-Italy"},{"site_id":672,"states":"-Viet Nam"},{"site_id":675,"states":"-El Salvador"},{"site_id":676,"states":"-Mexico"},{"site_id":677,"states":"-Philippines"},{"site_id":678,"states":"-Viet Nam"},{"site_id":682,"states":"-Uganda"},{"site_id":684,"states":"-Uganda"},{"site_id":685,"states":"-Spain"},{"site_id":686,"states":"-Canada"},{"site_id":687,"states":"-Germany"},{"site_id":688,"states":"-Japan"},{"site_id":690,"states":"-Czechia"},{"site_id":695,"states":"-Denmark"},{"site_id":696,"states":"-Denmark"},{"site_id":697,"states":"-Denmark"},{"site_id":698,"states":"-Australia"},{"site_id":699,"states":"-Luxembourg"},{"site_id":700,"states":"-Peru"},{"site_id":701,"states":"-Venezuela (Bolivarian Republic of)"},{"site_id":702,"states":"-Mexico"},{"site_id":703,"states":"-China"},{"site_id":704,"states":"-China"},{"site_id":705,"states":"-China"},{"site_id":707,"states":"-China"},{"site_id":708,"states":"-Georgia"},{"site_id":709,"states":"-Georgia"},{"site_id":710,"states":"-Georgia"},{"site_id":711,"states":"-Colombia"},{"site_id":712,"states":"-Italy"},{"site_id":714,"states":"-Mexico"},{"site_id":715,"states":"-Chile"},{"site_id":717,"states":"-Italy"},{"site_id":718,"states":"-Democratic Republic of the Congo"},{"site_id":719,"states":"-Russian Federation"},{"site_id":720,"states":"-Germany"},{"site_id":721,"states":"-United States of America"},{"site_id":722,"states":"-Philippines"},{"site_id":723,"states":"-Portugal"},{"site_id":724,"states":"-Serbia"},{"site_id":725,"states":"-Hungary-Slovakia"},{"site_id":726,"states":"-Italy"},{"site_id":728,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":729,"states":"-Germany"},{"site_id":730,"states":"-Italy"},{"site_id":731,"states":"-Sweden"},{"site_id":732,"states":"-Czechia"},{"site_id":733,"states":"-Italy"},{"site_id":734,"states":"-Japan"},{"site_id":736,"states":"-Republic of Korea"},{"site_id":737,"states":"-Republic of Korea"},{"site_id":738,"states":"-Republic of Korea"},{"site_id":739,"states":"-Netherlands"},{"site_id":740,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":741,"states":"-Canada"},{"site_id":742,"states":"-Colombia"},{"site_id":743,"states":"-Colombia"},{"site_id":744,"states":"-Colombia"},{"site_id":747,"states":"-Uruguay"},{"site_id":749,"states":"-Benin-Burkina Faso-Niger"},{"site_id":750,"states":"-Mauritania"},{"site_id":751,"states":"-Finland"},{"site_id":753,"states":"-Morocco"},{"site_id":754,"states":"-Russian Federation"},{"site_id":755,"states":"-Portugal"},{"site_id":757,"states":"-Ireland"},{"site_id":758,"states":"-Hungary"},{"site_id":759,"states":"-Netherlands"},{"site_id":761,"states":"-Gambia (the)"},{"site_id":762,"states":"-Sweden"},{"site_id":763,"states":"-Czechia"},{"site_id":764,"states":"-Belize"},{"site_id":765,"states":"-Russian Federation"},{"site_id":766,"states":"-Russian Federation"},{"site_id":768,"states":"-Russian Federation"},{"site_id":769,"states":"-Mongolia-Russian Federation"},{"site_id":770,"states":"-France"},{"site_id":772,"states":"-Austria-Hungary"},{"site_id":773,"states":"-France-Spain"},{"site_id":774,"states":"-Sweden"},{"site_id":775,"states":"-Japan"},{"site_id":776,"states":"-Japan"},{"site_id":777,"states":"-Armenia"},{"site_id":778,"states":"-China"},{"site_id":779,"states":"-China"},{"site_id":780,"states":"-Greece"},{"site_id":781,"states":"-Spain"},{"site_id":782,"states":"-Spain"},{"site_id":783,"states":"-Germany"},{"site_id":784,"states":"-Austria"},{"site_id":785,"states":"-Austria"},{"site_id":786,"states":"-Austria"},{"site_id":787,"states":"-Italy"},{"site_id":788,"states":"-Italy"},{"site_id":789,"states":"-Italy"},{"site_id":790,"states":"-Panama"},{"site_id":791,"states":"-Mexico"},{"site_id":792,"states":"-Mexico"},{"site_id":793,"states":"-Morocco"},{"site_id":794,"states":"-Tunisia"},{"site_id":795,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":797,"states":"-Italy"},{"site_id":798,"states":"-Bangladesh"},{"site_id":800,"states":"-Kenya"},{"site_id":801,"states":"-Kenya"},{"site_id":803,"states":"-Spain"},{"site_id":804,"states":"-Spain"},{"site_id":805,"states":"-Spain"},{"site_id":806,"states":"-Austria"},{"site_id":809,"states":"-Croatia"},{"site_id":810,"states":"-Croatia"},{"site_id":811,"states":"-China"},{"site_id":812,"states":"-China"},{"site_id":813,"states":"-China"},{"site_id":814,"states":"-Dominica"},{"site_id":815,"states":"-Mexico"},{"site_id":816,"states":"-Republic of Korea"},{"site_id":817,"states":"-Republic of Korea"},{"site_id":818,"states":"-Netherlands"},{"site_id":819,"states":"-Netherlands"},{"site_id":820,"states":"-Costa Rica"},{"site_id":821,"states":"-Brazil"},{"site_id":822,"states":"-Estonia"},{"site_id":823,"states":"-Italy"},{"site_id":824,"states":"-Italy"},{"site_id":825,"states":"-Italy"},{"site_id":826,"states":"-Italy"},{"site_id":827,"states":"-Italy"},{"site_id":828,"states":"-Italy"},{"site_id":829,"states":"-Italy"},{"site_id":830,"states":"-Italy"},{"site_id":831,"states":"-Italy"},{"site_id":832,"states":"-Italy"},{"site_id":833,"states":"-Italy"},{"site_id":835,"states":"-Poland"},{"site_id":836,"states":"-Morocco"},{"site_id":837,"states":"-Morocco"},{"site_id":839,"states":"-Cuba"},{"site_id":840,"states":"-Cuba"},{"site_id":841,"states":"-Cuba"},{"site_id":842,"states":"-Italy"},{"site_id":846,"states":"-Germany"},{"site_id":847,"states":"-Poland"},{"site_id":848,"states":"-Cyprus"},{"site_id":849,"states":"-Turkey"},{"site_id":850,"states":"-Lebanon"},{"site_id":852,"states":"-Latvia"},{"site_id":853,"states":"-Hungary"},{"site_id":854,"states":"-Solomon Islands"},{"site_id":855,"states":"-Belgium"},{"site_id":856,"states":"-Belgium"},{"site_id":857,"states":"-Belgium"},{"site_id":859,"states":"-Czechia"},{"site_id":860,"states":"-Czechia"},{"site_id":861,"states":"-Czechia"},{"site_id":862,"states":"-Mexico"},{"site_id":863,"states":"-Ecuador"},{"site_id":865,"states":"-Ukraine"},{"site_id":866,"states":"-Portugal-Spain"},{"site_id":867,"states":"-Netherlands"},{"site_id":868,"states":"-France"},{"site_id":870,"states":"-Japan"},{"site_id":871,"states":"-Sweden"},{"site_id":872,"states":"-France"},{"site_id":873,"states":"-France"},{"site_id":874,"states":"-Spain"},{"site_id":875,"states":"-Spain"},{"site_id":876,"states":"-Spain"},{"site_id":877,"states":"-New Zealand"},{"site_id":880,"states":"-China"},{"site_id":881,"states":"-China"},{"site_id":883,"states":"-Bolivia (Plurinational State of)"},{"site_id":884,"states":"-Switzerland"},{"site_id":885,"states":"-Uzbekistan"},{"site_id":886,"states":"-Turkmenistan"},{"site_id":887,"states":"-Papua New Guinea"},{"site_id":889,"states":"-Cuba"},{"site_id":890,"states":"-Brazil"},{"site_id":892,"states":"-Brazil"},{"site_id":893,"states":"-Brazil"},{"site_id":895,"states":"-Mexico"},{"site_id":896,"states":"-Germany"},{"site_id":897,"states":"-Germany"},{"site_id":898,"states":"-Finland-Sweden"},{"site_id":899,"states":"-Netherlands"},{"site_id":900,"states":"-Russian Federation"},{"site_id":901,"states":"-Czechia"},{"site_id":902,"states":"-Romania"},{"site_id":904,"states":"-Romania"},{"site_id":905,"states":"-Poland"},{"site_id":906,"states":"-Romania"},{"site_id":907,"states":"-Italy"},{"site_id":908,"states":"-Italy"},{"site_id":910,"states":"-Saint Kitts and Nevis"},{"site_id":911,"states":"-China"},{"site_id":912,"states":"-China"},{"site_id":913,"states":"-Japan"},{"site_id":914,"states":"-South Africa"},{"site_id":915,"states":"-South Africa"},{"site_id":916,"states":"-South Africa"},{"site_id":917,"states":"-Australia"},{"site_id":922,"states":"-India"},{"site_id":925,"states":"-India"},{"site_id":928,"states":"-Costa Rica"},{"site_id":929,"states":"-Spain"},{"site_id":930,"states":"-Spain"},{"site_id":931,"states":"-Austria"},{"site_id":932,"states":"-France"},{"site_id":933,"states":"-France"},{"site_id":934,"states":"-Portugal"},{"site_id":936,"states":"-Argentina"},{"site_id":937,"states":"-Argentina"},{"site_id":938,"states":"-Nigeria"},{"site_id":939,"states":"-Mexico"},{"site_id":940,"states":"-Suriname"},{"site_id":941,"states":"-Greece"},{"site_id":942,"states":"-Greece"},{"site_id":943,"states":"-Belgium-France"},{"site_id":944,"states":"-India"},{"site_id":945,"states":"-India"},{"site_id":946,"states":"-Bosnia and Herzegovina"},{"site_id":948,"states":"-Viet Nam"},{"site_id":949,"states":"-Viet Nam"},{"site_id":950,"states":"-Madagascar"},{"site_id":951,"states":"-Viet Nam"},{"site_id":954,"states":"-Egypt"},{"site_id":955,"states":"-Indonesia"},{"site_id":956,"states":"-Senegal"},{"site_id":958,"states":"-Azerbaijan"},{"site_id":959,"states":"-Chile"},{"site_id":960,"states":"-Armenia"},{"site_id":963,"states":"-Croatia"},{"site_id":965,"states":"-Netherlands"},{"site_id":966,"states":"-Argentina"},{"site_id":967,"states":"-Bolivia (Plurinational State of)"},{"site_id":968,"states":"-Sweden"},{"site_id":970,"states":"-Austria"},{"site_id":971,"states":"-Chile"},{"site_id":972,"states":"-Japan"},{"site_id":973,"states":"-Slovakia"},{"site_id":974,"states":"-Germany"},{"site_id":975,"states":"-Germany"},{"site_id":976,"states":"-Republic of Korea"},{"site_id":977,"states":"-Republic of Korea"},{"site_id":978,"states":"-Greece"},{"site_id":980,"states":"-Russian Federation"},{"site_id":981,"states":"-Russian Federation"},{"site_id":982,"states":"-Russian Federation"},{"site_id":983,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":984,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":985,"states":"-Lesotho-South Africa"},{"site_id":986,"states":"-Venezuela (Bolivarian Republic of)"},{"site_id":987,"states":"-Spain"},{"site_id":988,"states":"-Spain"},{"site_id":989,"states":"-Spain"},{"site_id":990,"states":"-Italy"},{"site_id":993,"states":"-Brazil"},{"site_id":994,"states":"-Lithuania-Russian Federation"},{"site_id":995,"states":"-Argentina"},{"site_id":996,"states":"-Belgium"},{"site_id":998,"states":"-Brazil"},{"site_id":999,"states":"-Brazil"},{"site_id":1000,"states":"-Brazil"},{"site_id":1001,"states":"-China"},{"site_id":1002,"states":"-China"},{"site_id":1003,"states":"-China"},{"site_id":1004,"states":"-China"},{"site_id":1005,"states":"-Belgium"},{"site_id":1006,"states":"-Belgium"},{"site_id":1007,"states":"-South Africa"},{"site_id":1008,"states":"-Cuba"},{"site_id":1009,"states":"-Belgium"},{"site_id":1010,"states":"-Oman"},{"site_id":1011,"states":"-Armenia"},{"site_id":1012,"states":"-Malaysia"},{"site_id":1013,"states":"-Malaysia"},{"site_id":1016,"states":"-Peru"},{"site_id":1017,"states":"-Suriname"},{"site_id":1018,"states":"-Turkey"},{"site_id":1021,"states":"-Botswana"},{"site_id":1022,"states":"-Uganda"},{"site_id":1023,"states":"-Russian Federation"},{"site_id":1024,"states":"-Italy"},{"site_id":1025,"states":"-Italy"},{"site_id":1026,"states":"-Italy"},{"site_id":1027,"states":"-Sweden"},{"site_id":1028,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1029,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1030,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1031,"states":"-Portugal"},{"site_id":1033,"states":"-Austria"},{"site_id":1035,"states":"-Brazil"},{"site_id":1037,"states":"-Switzerland"},{"site_id":1039,"states":"-China"},{"site_id":1040,"states":"-Israel"},{"site_id":1042,"states":"-Israel"},{"site_id":1044,"states":"-Spain"},{"site_id":1046,"states":"-Portugal"},{"site_id":1052,"states":"-Czechia"},{"site_id":1053,"states":"-Poland"},{"site_id":1054,"states":"-Poland"},{"site_id":1055,"states":"-Kenya"},{"site_id":1056,"states":"-India"},{"site_id":1058,"states":"-Morocco"},{"site_id":1060,"states":"-Kenya"},{"site_id":1061,"states":"-Mexico"},{"site_id":1063,"states":"-Hungary"},{"site_id":1066,"states":"-Germany"},{"site_id":1067,"states":"-Germany"},{"site_id":1068,"states":"-Italy"},{"site_id":1070,"states":"-Russian Federation"},{"site_id":1073,"states":"-Sudan"},{"site_id":1076,"states":"-Azerbaijan"},{"site_id":1077,"states":"-Iran (Islamic Republic of)"},{"site_id":1078,"states":"-Czechia"},{"site_id":1079,"states":"-Mexico"},{"site_id":1081,"states":"-Mongolia"},{"site_id":1083,"states":"-China"},{"site_id":1084,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1087,"states":"-Germany"},{"site_id":1090,"states":"-Italy-Switzerland"},{"site_id":1091,"states":"-Democratic People's Republic of Korea"},{"site_id":1093,"states":"-Jordan"},{"site_id":1094,"states":"-Australia"},{"site_id":1096,"states":"-Israel"},{"site_id":1097,"states":"-Russian Federation"},{"site_id":1099,"states":"-South Africa"},{"site_id":1100,"states":"-Brazil"},{"site_id":1101,"states":"-India"},{"site_id":1102,"states":"-Kazakhstan"},{"site_id":1103,"states":"-Kazakhstan"},{"site_id":1106,"states":"-Iran (Islamic Republic of)"},{"site_id":1107,"states":"-Israel"},{"site_id":1108,"states":"-Israel"},{"site_id":1110,"states":"-China"},{"site_id":1111,"states":"-China"},{"site_id":1112,"states":"-China"},{"site_id":1113,"states":"-China"},{"site_id":1114,"states":"-China"},{"site_id":1115,"states":"-France"},{"site_id":1116,"states":"-Argentina"},{"site_id":1117,"states":"-Portugal"},{"site_id":1118,"states":"-Nigeria"},{"site_id":1121,"states":"-Colombia"},{"site_id":1127,"states":"-Germany-Poland"},{"site_id":1130,"states":"-Iraq"},{"site_id":1131,"states":"-Australia"},{"site_id":1133,"states":"-Albania-Austria-Belgium-Bulgaria-Croatia-Germany-Italy-Romania-Slovakia-Slovenia-Spain-Ukraine"},{"site_id":1134,"states":"-Sweden"},{"site_id":1135,"states":"-China"},{"site_id":1136,"states":"-Mexico"},{"site_id":1137,"states":"-Lithuania"},{"site_id":1138,"states":"-Panama"},{"site_id":1139,"states":"-Mali"},{"site_id":1140,"states":"-Togo"},{"site_id":1141,"states":"-Tajikistan"},{"site_id":1142,"states":"-Japan"},{"site_id":1143,"states":"-Norway"},{"site_id":1145,"states":"-Kazakhstan"},{"site_id":1147,"states":"-Gabon"},{"site_id":1149,"states":"-Denmark"},{"site_id":1150,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1152,"states":"-Iceland"},{"site_id":1153,"states":"-France"},{"site_id":1155,"states":"-Germany"},{"site_id":1158,"states":"-Italy"},{"site_id":1160,"states":"-Andorra"},{"site_id":1161,"states":"-Saint Lucia"},{"site_id":1162,"states":"-South Africa"},{"site_id":1165,"states":"-Poland"},{"site_id":1167,"states":"-Indonesia"},{"site_id":1170,"states":"-Russian Federation"},{"site_id":1174,"states":"-Colombia"},{"site_id":1178,"states":"-Chile"},{"site_id":1179,"states":"-Switzerland"},{"site_id":1181,"states":"-France"},{"site_id":1182,"states":"-Mexico"},{"site_id":1183,"states":"-United Republic of Tanzania"},{"site_id":1185,"states":"-Belgium"},{"site_id":1186,"states":"-Egypt"},{"site_id":1187,"states":"-Belarus-Estonia-Finland-Latvia-Lithuania-Norway-Republic of Moldova-Russian Federation-Sweden-Ukraine"},{"site_id":1188,"states":"-Iran (Islamic Republic of)"},{"site_id":1189,"states":"-Ethiopia"},{"site_id":1192,"states":"-Bahrain"},{"site_id":1193,"states":"-Japan"},{"site_id":1194,"states":"-Indonesia"},{"site_id":1195,"states":"-Norway"},{"site_id":1196,"states":"-Belarus"},{"site_id":1199,"states":"-Turkmenistan"},{"site_id":1200,"states":"-Italy"},{"site_id":1202,"states":"-Cuba"},{"site_id":1203,"states":"-Sri Lanka"},{"site_id":1207,"states":"-Oman"},{"site_id":1208,"states":"-Iran (Islamic Republic of)"},{"site_id":1209,"states":"-Mexico"},{"site_id":1211,"states":"-Italy"},{"site_id":1213,"states":"-China"},{"site_id":1214,"states":"-Chile"},{"site_id":1215,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1216,"states":"-Colombia"},{"site_id":1217,"states":"-Spain"},{"site_id":1220,"states":"-Israel"},{"site_id":1221,"states":"-Canada"},{"site_id":1222,"states":"-Iran (Islamic Republic of)"},{"site_id":1223,"states":"-Malaysia"},{"site_id":1224,"states":"-Cambodia"},{"site_id":1225,"states":"-Burkina Faso"},{"site_id":1226,"states":"-Gambia (the)-Senegal"},{"site_id":1227,"states":"-Mauritius"},{"site_id":1229,"states":"-Syrian Arab Republic"},{"site_id":1230,"states":"-Kyrgyzstan"},{"site_id":1231,"states":"-Kenya"},{"site_id":1234,"states":"-Russian Federation"},{"site_id":1236,"states":"-Nicaragua"},{"site_id":1237,"states":"-Italy"},{"site_id":1239,"states":"-Germany"},{"site_id":1240,"states":"-Croatia"},{"site_id":1242,"states":"-Turkmenistan"},{"site_id":1243,"states":"-Switzerland"},{"site_id":1245,"states":"-San Marino"},{"site_id":1246,"states":"-Japan"},{"site_id":1248,"states":"-China"},{"site_id":1250,"states":"-Mexico"},{"site_id":1252,"states":"-Tajikistan"},{"site_id":1253,"states":"-Serbia"},{"site_id":1255,"states":"-Namibia"},{"site_id":1256,"states":"-France"},{"site_id":1257,"states":"-Madagascar"},{"site_id":1258,"states":"-Spain"},{"site_id":1259,"states":"-Mauritius"},{"site_id":1260,"states":"-Bosnia and Herzegovina"},{"site_id":1262,"states":"-Iran (Islamic Republic of)"},{"site_id":1263,"states":"-Yemen"},{"site_id":1264,"states":"-Republic of Korea"},{"site_id":1265,"states":"-South Africa"},{"site_id":1267,"states":"-Iceland"},{"site_id":1268,"states":"-Niger"},{"site_id":1269,"states":"-Peru"},{"site_id":1270,"states":"-Cuba"},{"site_id":1272,"states":"-Brazil"},{"site_id":1273,"states":"-Slovakia"},{"site_id":1274,"states":"-Mexico"},{"site_id":1276,"states":"-Italy-Switzerland"},{"site_id":1277,"states":"-Japan"},{"site_id":1278,"states":"-Democratic People's Republic of Korea"},{"site_id":1279,"states":"-China"},{"site_id":1280,"states":"-Vanuatu"},{"site_id":1282,"states":"-Sweden"},{"site_id":1283,"states":"-France"},{"site_id":1285,"states":"-Canada"},{"site_id":1287,"states":"-Italy"},{"site_id":1290,"states":"-Mexico"},{"site_id":1292,"states":"-China"},{"site_id":1293,"states":"-Saudi Arabia"},{"site_id":1295,"states":"-Kenya"},{"site_id":1298,"states":"-Belgium"},{"site_id":1299,"states":"-Russian Federation"},{"site_id":1302,"states":"-Switzerland"},{"site_id":1303,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1305,"states":"-China"},{"site_id":1306,"states":"-Australia"},{"site_id":1308,"states":"-Brazil"},{"site_id":1310,"states":"-Cabo Verde"},{"site_id":1312,"states":"-Spain"},{"site_id":1313,"states":"-Slovenia-Spain"},{"site_id":1314,"states":"-Denmark-Germany-Netherlands"},{"site_id":1315,"states":"-Iran (Islamic Republic of)"},{"site_id":1317,"states":"-France"},{"site_id":1318,"states":"-Italy"},{"site_id":1319,"states":"-Republic of Korea"},{"site_id":1321,"states":"-Argentina-Belgium-France-Germany-India-Japan-Switzerland"},{"site_id":1322,"states":"-Côte d'Ivoire"},{"site_id":1324,"states":"-Republic of Korea"},{"site_id":1325,"states":"-Kiribati"},{"site_id":1326,"states":"-United States of America"},{"site_id":1328,"states":"-Viet Nam"},{"site_id":1329,"states":"-Saudi Arabia"},{"site_id":1330,"states":"-Ukraine"},{"site_id":1333,"states":"-Ethiopia"},{"site_id":1334,"states":"-China"},{"site_id":1335,"states":"-China"},{"site_id":1336,"states":"-Sudan"},{"site_id":1337,"states":"-France"},{"site_id":1338,"states":"-India"},{"site_id":1339,"states":"-Marshall Islands"},{"site_id":1342,"states":"-India"},{"site_id":1343,"states":"-United Arab Emirates"},{"site_id":1344,"states":"-Belgium"},{"site_id":1345,"states":"-Iran (Islamic Republic of)"},{"site_id":1346,"states":"-Iran (Islamic Republic of)"},{"site_id":1348,"states":"-Syrian Arab Republic"},{"site_id":1349,"states":"-Netherlands"},{"site_id":1351,"states":"-Mexico"},{"site_id":1352,"states":"-Mexico"},{"site_id":1356,"states":"-Jamaica"},{"site_id":1358,"states":"-Viet Nam"},{"site_id":1359,"states":"-Senegal"},{"site_id":1360,"states":"-France"},{"site_id":1361,"states":"-Saudi Arabia"},{"site_id":1362,"states":"-Japan"},{"site_id":1363,"states":"-Austria-France-Germany-Italy-Slovenia-Switzerland"},{"site_id":1364,"states":"-Bahrain"},{"site_id":1366,"states":"-Turkey"},{"site_id":1367,"states":"-Portugal"},{"site_id":1368,"states":"-Germany"},{"site_id":1369,"states":"-Australia"},{"site_id":1370,"states":"-Israel"},{"site_id":1371,"states":"-Spain"},{"site_id":1372,"states":"-Iran (Islamic Republic of)"},{"site_id":1376,"states":"-Barbados"},{"site_id":1377,"states":"-Jordan"},{"site_id":1379,"states":"-Germany"},{"site_id":1380,"states":"-Cameroon-Central African Republic-Congo"},{"site_id":1382,"states":"-Mongolia"},{"site_id":1386,"states":"-Palau"},{"site_id":1387,"states":"-Portugal"},{"site_id":1388,"states":"-China"},{"site_id":1389,"states":"-China"},{"site_id":1390,"states":"-Italy"},{"site_id":1393,"states":"-Israel"},{"site_id":1396,"states":"-Malaysia"},{"site_id":1397,"states":"-Iran (Islamic Republic of)"},{"site_id":1398,"states":"-Iran (Islamic Republic of)"},{"site_id":1399,"states":"-Fiji"},{"site_id":1400,"states":"-Chad"},{"site_id":1401,"states":"-Morocco"},{"site_id":1402,"states":"-Qatar"},{"site_id":1403,"states":"-Philippines"},{"site_id":1404,"states":"-Canada"},{"site_id":1405,"states":"-Turkey"},{"site_id":1406,"states":"-India"},{"site_id":1407,"states":"-Senegal"},{"site_id":1410,"states":"-Mexico"},{"site_id":1411,"states":"-Ukraine"},{"site_id":1412,"states":"-Canada"},{"site_id":1413,"states":"-Germany"},{"site_id":1414,"states":"-China"},{"site_id":1415,"states":"-Canada"},{"site_id":1416,"states":"-Denmark"},{"site_id":1418,"states":"-Japan"},{"site_id":1422,"states":"-Iran (Islamic Republic of)"},{"site_id":1423,"states":"-Iran (Islamic Republic of)"},{"site_id":1424,"states":"-Poland-Ukraine"},{"site_id":1425,"states":"-France"},{"site_id":1426,"states":"-France"},{"site_id":1427,"states":"-Italy"},{"site_id":1430,"states":"-Namibia"},{"site_id":1432,"states":"-Botswana"},{"site_id":1433,"states":"-Palestine"},{"site_id":1434,"states":"-France"},{"site_id":1435,"states":"-United States of America"},{"site_id":1437,"states":"-Iraq"},{"site_id":1438,"states":"-Viet Nam"},{"site_id":1439,"states":"-Republic of Korea"},{"site_id":1440,"states":"-Mongolia"},{"site_id":1441,"states":"-Netherlands"},{"site_id":1442,"states":"-China-Kazakhstan-Kyrgyzstan"},{"site_id":1443,"states":"-China"},{"site_id":1444,"states":"-Myanmar"},{"site_id":1446,"states":"-Jordan"},{"site_id":1447,"states":"-Germany"},{"site_id":1448,"states":"-Mongolia-Russian Federation"},{"site_id":1449,"states":"-Japan"},{"site_id":1450,"states":"-Kenya"},{"site_id":1452,"states":"-Turkey"},{"site_id":1453,"states":"-Costa Rica"},{"site_id":1455,"states":"-Iran (Islamic Republic of)"},{"site_id":1456,"states":"-Iran (Islamic Republic of)"},{"site_id":1457,"states":"-Turkey"},{"site_id":1459,"states":"-Argentina-Bolivia (Plurinational State of)-Chile-Colombia-Ecuador-Peru"},{"site_id":1463,"states":"-Mexico"},{"site_id":1464,"states":"-Uruguay"},{"site_id":1465,"states":"-France"},{"site_id":1466,"states":"-United States of America"},{"site_id":1467,"states":"-Germany"},{"site_id":1468,"states":"-Denmark"},{"site_id":1469,"states":"-Denmark"},{"site_id":1470,"states":"-Germany"},{"site_id":1471,"states":"-Israel"},{"site_id":1472,"states":"-Saudi Arabia"},{"site_id":1474,"states":"-China"},{"site_id":1475,"states":"-Chad"},{"site_id":1477,"states":"-Republic of Korea"},{"site_id":1478,"states":"-Czechia-Germany"},{"site_id":1480,"states":"-India"},{"site_id":1481,"states":"-Iraq"},{"site_id":1483,"states":"-Singapore"},{"site_id":1484,"states":"-Japan"},{"site_id":1485,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1486,"states":"-Norway"},{"site_id":1487,"states":"-Italy"},{"site_id":1488,"states":"-Turkey"},{"site_id":1490,"states":"-Kazakhstan-Kyrgyzstan-Uzbekistan"},{"site_id":1492,"states":"-Palestine"},{"site_id":1493,"states":"-Brazil"},{"site_id":1495,"states":"-Japan"},{"site_id":1496,"states":"-United States of America"},{"site_id":1497,"states":"-Canada"},{"site_id":1498,"states":"-Republic of Korea"},{"site_id":1499,"states":"-Antigua and Barbuda"},{"site_id":1500,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1501,"states":"-Spain"},{"site_id":1502,"states":"-India"},{"site_id":1503,"states":"-Micronesia (Federated States of)"},{"site_id":1504,"states":"-Bosnia and Herzegovina-Croatia-Serbia-Montenegro"},{"site_id":1505,"states":"-Iran (Islamic Republic of)"},{"site_id":1506,"states":"-Iran (Islamic Republic of)"},{"site_id":1508,"states":"-China"},{"site_id":1509,"states":"-China"},{"site_id":1510,"states":"-Mexico"},{"site_id":1511,"states":"-Angola"},{"site_id":1513,"states":"-India"},{"site_id":1517,"states":"-Greece"},{"site_id":1518,"states":"-Turkey"},{"site_id":1519,"states":"-Turkey"},{"site_id":1523,"states":"-Russian Federation"},{"site_id":1525,"states":"-Russian Federation"},{"site_id":1526,"states":"-Argentina"},{"site_id":1527,"states":"-Germany"},{"site_id":1529,"states":"-France"},{"site_id":1532,"states":"-Cambodia"},{"site_id":1533,"states":"-Croatia-Italy-Montenegro"},{"site_id":1534,"states":"-Mexico"},{"site_id":1535,"states":"-Japan"},{"site_id":1536,"states":"-Denmark"},{"site_id":1537,"states":"-Oman"},{"site_id":1538,"states":"-Italy"},{"site_id":1539,"states":"-Poland"},{"site_id":1540,"states":"-China"},{"site_id":1541,"states":"-China"},{"site_id":1542,"states":"-Bahrain"},{"site_id":1544,"states":"-Iran (Islamic Republic of)"},{"site_id":1545,"states":"-South Africa"},{"site_id":1548,"states":"-Brazil"},{"site_id":1549,"states":"-Azerbaijan"},{"site_id":1550,"states":"-Eritrea"},{"site_id":1551,"states":"-India"},{"site_id":1553,"states":"-Germany"},{"site_id":1557,"states":"-Denmark"},{"site_id":1559,"states":"-China"},{"site_id":1560,"states":"-Spain"},{"site_id":1562,"states":"-Republic of Korea"},{"site_id":1563,"states":"-Saudi Arabia"},{"site_id":1565,"states":"-Palestine"},{"site_id":1568,"states":"-Iran (Islamic Republic of)"},{"site_id":1571,"states":"-Italy"},{"site_id":1572,"states":"-Turkey"},{"site_id":1573,"states":"-Portugal"},{"site_id":1575,"states":"-South Africa"},{"site_id":1577,"states":"-Australia"},{"site_id":1578,"states":"-Spain"},{"site_id":1580,"states":"-Germany"},{"site_id":1584,"states":"-Iran (Islamic Republic of)"},{"site_id":1587,"states":"-Lao People's Democratic Republic"},{"site_id":1588,"states":"-Myanmar"},{"site_id":1589,"states":"-Czechia"},{"site_id":1590,"states":"-Portugal"},{"site_id":1592,"states":"-China"},{"site_id":1593,"states":"-Japan"},{"site_id":1594,"states":"-United Kingdom of Great Britain and Northern Ireland"},{"site_id":1597,"states":"-Canada"},{"site_id":1599,"states":"-Poland"},{"site_id":1602,"states":"-Burkina Faso"},{"site_id":1603,"states":"-France"},{"site_id":1604,"states":"-Iceland"},{"site_id":1605,"states":"-India"},{"site_id":1606,"states":"-China"},{"site_id":1610,"states":"-Indonesia"}]

# Dictionnaire pays -> continent (insère ici le dictionnaire complet généré)
country_to_continent = {
    "Afghanistan": "Asia",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Andorra": "Europe",
    "Angola": "Africa",
    "Antigua and Barbuda": "North America",
    "Argentina": "South America",
    "Armenia": "Asia",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Azerbaijan": "Asia",
    "Bahamas": "North America",
    "Bahrain": "Asia",
    "Bangladesh": "Asia",
    "Barbados": "North America",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Belize": "North America",
    "Benin": "Africa",
    "Bhutan": "Asia",
    "Bolivia": "South America",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "South America",
    "Brunei": "Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cabo Verde": "Africa",
    "Cambodia": "Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Chile": "South America",
    "China": "Asia",
    "Colombia": "South America",
    "Comoros": "Africa",
    "Congo (Congo-Brazzaville)": "Africa",
    "Costa Rica": "North America",
    "Croatia": "Europe",
    "Cuba": "North America",
    "Cyprus": "Asia",
    "Czechia (Czech Republic)": "Europe",
    "Democratic Republic of the Congo": "Africa",
    "Denmark": "Europe",
    "Djibouti": "Africa",
    "Dominica": "North America",
    "Dominican Republic": "North America",
    "Ecuador": "South America",
    "Egypt": "Africa",
    "El Salvador": "North America",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Europe",
    "Eswatini (fmr. Swaziland)": "Africa",
    "Ethiopia": "Africa",
    "Fiji": "Oceania",
    "Finland": "Europe",
    "France": "Europe",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Asia",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Greece": "Europe",
    "Grenada": "North America",
    "Guatemala": "North America",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Guyana": "South America",
    "Haiti": "North America",
    "Honduras": "North America",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Ireland": "Europe",
    "Israel": "Asia",
    "Italy": "Europe",
    "Jamaica": "North America",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Kenya": "Africa",
    "Kiribati": "Oceania",
    "Kuwait": "Asia",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Asia",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Libya": "Africa",
    "Liechtenstein": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Marshall Islands": "Oceania",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mexico": "North America",
    "Micronesia": "Oceania",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Myanmar (formerly Burma)": "Asia",
    "Namibia": "Africa",
    "Nauru": "Oceania",
    "Nepal": "Asia",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nicaragua": "North America",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "North Korea": "Asia",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Palau": "Oceania",
    "Palestine State": "Asia",
    "Panama": "North America",
    "Papua New Guinea": "Oceania",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "Asia",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Qatar": "Asia",
    "Romania": "Europe",
    "Russia": "Europe",
    "Rwanda": "Africa",
    "Saint Kitts and Nevis": "North America",
    "Saint Lucia": "North America",
    "Saint Vincent and the Grenadines": "North America",
    "Samoa": "Oceania",
    "San Marino": "Europe",
    "Sao Tome and Principe": "Africa",
    "Saudi Arabia": "Asia",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Solomon Islands": "Oceania",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "South Korea": "Asia",
    "South Sudan": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Sudan": "Africa",
    "Suriname": "South America",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Syria": "Asia",
    "Tajikistan": "Asia",
    "Tanzania": "Africa",
    "Thailand": "Asia",
    "Timor-Leste": "Asia",
    "Togo": "Africa",
    "Tonga": "Oceania",
    "Trinidad and Tobago": "North America",
    "Tunisia": "Africa",
    "Turkey": "Asia",
    "Turkmenistan": "Asia",
    "Tuvalu": "Oceania",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Asia",
    "United Kingdom": "Europe",
    "United States of America": "North America",
    "Uruguay": "South America",
    "Uzbekistan": "Asia",
    "Vanuatu": "Oceania",
    "Vatican City": "Europe",
    "Venezuela": "South America",
    "Vietnam": "Asia",
    "Yemen": "Asia",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",
    "Syrian Arab Republic": "Asia",
    "United Republic of Tanzania": "Africa",
    "Iran (Islamic Republic of)": "Asia",
    "Jerusalem (Site proposed by Jordan)": "Asia",
    "Côte d'Ivoire-Guinea": "Africa",
    "Côte d'Ivoire": "Africa",
    "United Kingdom of Great Britain and Northern Ireland": "Europe",
    "Bolivia (Plurinational State of)": "South America",
    "Lao People's Democratic Republic": "Asia",
    "Russian Federation": "Russia",
    "Czechia": "Europe",
    "Venezuela (Bolivarian Republic of)": "South America",
    "Viet Nam": "Asia",
    "Republic of Korea": "Asia",
    "Gambia (the)": "Africa",
    "Democratic People's Republic of Korea": "Asia",
    "Gambia (the)-Senegal": "Africa",
    "Palestine": "Asia",
    "Myanmar": "Asia",
    "Micronesia (Federated States of)": "Oceania",
    "Holy See-Italy": "Europe",
    "Holy See": "Europe"
}


# Connexion à la base de données
conn = mysql.connector.connect(
    host="localhost",  # Remplace par l'hôte Docker si nécessaire
    port=6035,         # Vérifie que le port est correct
    user="root",       # Remplace par ton utilisateur MySQL
    password="root",   # Remplace par ton mot de passe MySQL
    database="db_unesco"  # Remplace par le nom de ta base de données
)
cursor = conn.cursor()

# Traitement des données
for item in data:
    site_id = item['site_id']
    
    # Extraire le premier pays de la chaîne
    states = item['states'].lstrip('-')
    first_country = states.split('-')[0].strip()
    
    continent = country_to_continent.get(first_country)

    if continent:
        query = """
            UPDATE t_sites
            SET continent = %s
            WHERE site_id = %s
        """
        cursor.execute(query, (continent, site_id))
        print(f"[✓] Site {site_id} → {first_country} → {continent}")
    else:
        print(f"[!] Pays inconnu pour le site_id {site_id} : '{first_country}'")

# Commit et fermeture
conn.commit()
cursor.close()
conn.close()
print("Mise à jour terminée.")